"use client";

import { useState } from "react";
import { cn } from "@/lib/utils";
import {
  Plus,
  Search,
  FileText,
  FileCode,
  FileJson,
  File,
  Bot,
  Clock,
  Download,
  Eye,
  MoreHorizontal,
  FolderOpen,
  Grid3x3,
  List,
} from "lucide-react";

interface Doc {
  id: string;
  name: string;
  type: "md" | "ts" | "json" | "txt";
  size: string;
  agent?: string;
  updatedAt: string;
  description: string;
  tags: string[];
}

const DOCUMENTS: Doc[] = [
  {
    id: "1",
    name: "API_REFERENCE.md",
    type: "md",
    size: "24 KB",
    agent: "Agent-1",
    updatedAt: "1h ago",
    description:
      "Full REST API reference with endpoint docs, request/response schemas, and auth examples.",
    tags: ["api", "docs"],
  },
  {
    id: "2",
    name: "auth.middleware.ts",
    type: "ts",
    size: "8 KB",
    agent: "Agent-1",
    updatedAt: "2h ago",
    description:
      "JWT authentication middleware with refresh token rotation and rate limiting.",
    tags: ["auth", "backend"],
  },
  {
    id: "3",
    name: "agent_config.json",
    type: "json",
    size: "2 KB",
    updatedAt: "3h ago",
    description:
      "Agent configuration manifest — model settings, tool permissions, memory limits.",
    tags: ["config", "agents"],
  },
  {
    id: "4",
    name: "ARCHITECTURE.md",
    type: "md",
    size: "18 KB",
    agent: "Agent-3",
    updatedAt: "6h ago",
    description:
      "System architecture overview covering frontend, WebSocket layer, agent hook, and data model.",
    tags: ["docs", "infra"],
  },
  {
    id: "5",
    name: "memory_schema.ts",
    type: "ts",
    size: "6 KB",
    agent: "Agent-3",
    updatedAt: "1d ago",
    description:
      "TypeScript types and Zod schemas for the memory system, including vector metadata.",
    tags: ["memory", "types"],
  },
  {
    id: "6",
    name: "cost_report.txt",
    type: "txt",
    size: "4 KB",
    updatedAt: "2d ago",
    description: "Weekly token usage and cost breakdown per agent and project.",
    tags: ["billing", "analytics"],
  },
];

const FILE_ICONS = {
  md: FileText,
  ts: FileCode,
  json: FileJson,
  txt: File,
};

const FILE_COLORS = {
  md: "bg-indigo-50 text-indigo-500",
  ts: "bg-blue-50 text-blue-500",
  json: "bg-amber-50 text-amber-500",
  txt: "bg-slate-100 text-slate-500",
};

const FILE_BADGE = {
  md: "bg-indigo-50 text-indigo-600 border-indigo-100",
  ts: "bg-blue-50 text-blue-600 border-blue-100",
  json: "bg-amber-50 text-amber-600 border-amber-100",
  txt: "bg-slate-50 text-slate-500 border-slate-100",
};

export default function DocumentsView() {
  const [query, setQuery] = useState("");
  const [view, setView] = useState<"grid" | "list">("list");

  const filtered = DOCUMENTS.filter(
    (d) =>
      query === "" ||
      d.name.toLowerCase().includes(query.toLowerCase()) ||
      d.description.toLowerCase().includes(query.toLowerCase()) ||
      d.tags.some((t) => t.includes(query.toLowerCase())),
  );

  return (
    <div className="space-y-5 max-w-[1000px]">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-xl font-semibold text-slate-900">Documents</h1>
          <p className="text-sm text-slate-400 mt-0.5">
            {DOCUMENTS.length} files generated by agents
          </p>
        </div>
        <button className="flex items-center gap-1.5 text-xs font-medium text-white bg-slate-900 hover:bg-slate-700 px-3 py-2 rounded-lg transition-colors">
          <Plus className="w-3.5 h-3.5" />
          Upload
        </button>
      </div>

      {/* Toolbar */}
      <div className="flex items-center gap-3">
        <div className="relative flex-1">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-300" />
          <input
            type="text"
            placeholder="Search documents..."
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            className="w-full pl-9 pr-4 py-2.5 text-sm border border-slate-200 rounded-xl bg-white placeholder-slate-300 focus:outline-none focus:border-indigo-300 focus:ring-2 focus:ring-indigo-50 transition-all"
          />
        </div>
        <div className="flex items-center bg-white border border-slate-100 rounded-lg p-0.5">
          <button
            onClick={() => setView("list")}
            className={cn(
              "p-1.5 rounded-md transition-colors",
              view === "list"
                ? "bg-slate-900 text-white"
                : "text-slate-400 hover:text-slate-600",
            )}
          >
            <List className="w-3.5 h-3.5" />
          </button>
          <button
            onClick={() => setView("grid")}
            className={cn(
              "p-1.5 rounded-md transition-colors",
              view === "grid"
                ? "bg-slate-900 text-white"
                : "text-slate-400 hover:text-slate-600",
            )}
          >
            <Grid3x3 className="w-3.5 h-3.5" />
          </button>
        </div>
      </div>

      {view === "list" ? (
        <div className="bg-white border border-slate-100 rounded-xl overflow-hidden">
          {/* Table header */}
          <div className="grid grid-cols-[2fr_1fr_1fr_80px_100px] gap-4 px-4 py-2.5 border-b border-slate-100 bg-slate-50/60">
            {["Name", "Agent", "Updated", "Size", ""].map((h) => (
              <span
                key={h}
                className="text-[10px] font-semibold uppercase tracking-wider text-slate-400"
              >
                {h}
              </span>
            ))}
          </div>
          <div className="divide-y divide-slate-50">
            {filtered.map((doc) => {
              const Icon = FILE_ICONS[doc.type];
              return (
                <div
                  key={doc.id}
                  className="grid grid-cols-[2fr_1fr_1fr_80px_100px] gap-4 px-4 py-3 hover:bg-slate-50/60 transition-colors group items-center"
                >
                  {/* Name */}
                  <div className="flex items-center gap-3 min-w-0">
                    <div
                      className={cn(
                        "w-8 h-8 rounded-lg flex items-center justify-center shrink-0",
                        FILE_COLORS[doc.type],
                      )}
                    >
                      <Icon className="w-4 h-4" />
                    </div>
                    <div className="min-w-0">
                      <p className="text-sm font-medium text-slate-800 truncate">
                        {doc.name}
                      </p>
                      <p className="text-[11px] text-slate-400 truncate">
                        {doc.description}
                      </p>
                    </div>
                  </div>

                  {/* Agent */}
                  <div>
                    {doc.agent ? (
                      <span className="flex items-center gap-1 text-xs text-slate-500">
                        <Bot className="w-3 h-3" />
                        {doc.agent}
                      </span>
                    ) : (
                      <span className="text-xs text-slate-300">—</span>
                    )}
                  </div>

                  {/* Updated */}
                  <span className="flex items-center gap-1 text-xs text-slate-400">
                    <Clock className="w-3 h-3" />
                    {doc.updatedAt}
                  </span>

                  {/* Size */}
                  <span className="text-xs text-slate-400">{doc.size}</span>

                  {/* Actions */}
                  <div className="flex items-center gap-1 justify-end opacity-0 group-hover:opacity-100 transition-opacity">
                    <button className="w-7 h-7 rounded-md flex items-center justify-center text-slate-400 hover:bg-slate-100 transition-colors">
                      <Eye className="w-3.5 h-3.5" />
                    </button>
                    <button className="w-7 h-7 rounded-md flex items-center justify-center text-slate-400 hover:bg-slate-100 transition-colors">
                      <Download className="w-3.5 h-3.5" />
                    </button>
                    <button className="w-7 h-7 rounded-md flex items-center justify-center text-slate-400 hover:bg-slate-100 transition-colors">
                      <MoreHorizontal className="w-3.5 h-3.5" />
                    </button>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      ) : (
        <div className="grid grid-cols-3 gap-3">
          {filtered.map((doc) => {
            const Icon = FILE_ICONS[doc.type];
            return (
              <div
                key={doc.id}
                className="bg-white border border-slate-100 rounded-xl p-4 hover:border-slate-200 hover:shadow-sm transition-all group cursor-pointer"
              >
                <div className="flex items-start justify-between mb-3">
                  <div
                    className={cn(
                      "w-9 h-9 rounded-xl flex items-center justify-center",
                      FILE_COLORS[doc.type],
                    )}
                  >
                    <Icon className="w-4.5 h-4.5" />
                  </div>
                  <span
                    className={cn(
                      "text-[10px] font-semibold px-1.5 py-0.5 rounded-full border uppercase",
                      FILE_BADGE[doc.type],
                    )}
                  >
                    .{doc.type}
                  </span>
                </div>
                <p className="text-sm font-semibold text-slate-800 truncate mb-1">
                  {doc.name}
                </p>
                <p className="text-[11px] text-slate-400 leading-relaxed line-clamp-2 mb-3">
                  {doc.description}
                </p>
                <div className="flex items-center justify-between text-[11px] text-slate-400">
                  <span>{doc.size}</span>
                  <span>{doc.updatedAt}</span>
                </div>
              </div>
            );
          })}
        </div>
      )}

      {filtered.length === 0 && (
        <div className="flex flex-col items-center justify-center h-40 text-center bg-white rounded-xl border border-slate-100">
          <FolderOpen className="w-8 h-8 text-slate-200 mb-2" />
          <p className="text-sm text-slate-400">No documents found</p>
        </div>
      )}
    </div>
  );
}
